erpc/erpc

upstream/alchemy_http_json_rpc_client.go
vendors/infura.go

Correct the alchemy rpc endpoint rebuilt url for type `evm-alchemy` or for url starting with `evm+alchemy://xxx` or `alchemy://xxx` endpoints.
The `alchemyapi.io` endpoint don't work on all the chains, for example with `arb-sepolia` or `base-mainnet` it's ko

fix: alchemy rpc endpoint

---

erpc/evm_json_rpc_cache.go
erpc/evm_json_rpc_cache_test.go
evm/block_ref.go
evm/block_ref_test.go

`blockNumber` or `blockHash` in request:
`blockNumber` or `blockHash` in response:

feat: extending rpc json methods for caching

---

common/evm_json_rpc.go

The normalization code tries to normalize the block number for `eth_getStorageAt` but incorrectly thinks that the block number is the second parameter. It's actually the third. This causes any storage request to fail.

fix: invalid normalization for eth_getStorageAt

---

common/evm_block_ref.go

When setting response cache, `eth_chainId` has block ref set to `all`:
https://github.com/erpc/erpc/blob/f214de4266d0d86ac33356668ef0e4f32bf3a1aa/common/evm_block_ref.go#L158-L162
However, when fetching cache entry, `eth_chainId` falls under this branch:
https://github.com/erpc/erpc/blob/f214de4266d0d86ac33356668ef0e4f32bf3a1aa/erpc/evm_json_rpc_cache.go#L74-L76
This results in the chain ID request successfully getting cached but never used. This PR fixes it by setting the same block ref as in the response.

fix: cache never used for `eth_chainId`

---

.github/workflows/release.yml

Makes the Docker image building part of the release pipeline parameterized, just so that forks can make their own Docker images.
The extra `tag_param` step is necessary as GitHub Actions expressions do not allow string case manipulation, but here we need the lower case ref of the repo.
The change has been tested. A successful run can be found [here](https://github.com/xJonathanLEI/erpc/actions/runs/10647714084/job/29515953574) (apparently ignore the `release` job).

ci: parameterize docker image tags

---

common/request.go
erpc/evm_json_rpc_cache.go
erpc/evm_json_rpc_cache_test.go
erpc/networks_test.go

Related to https://github.com/erpc/erpc/issues/55

feat: cache empty responses for synced and finalized blocks

---

erpc/networks_test.go
upstream/registry_test.go

if `SupportsNetwork` for certain upstreams can throw an error (e.g a bad response from `eth_chainId` method to validate the network support), we shouldn't throw and stop the flow and must go to the next upstream.

test: prepare upstreams with unsupported network

---

erpc/http_server.go

Passing the enriched logger (`lg`) instead of the base logger (`s.logger`). By doing so, error logs will include additional context fields like projectId, architecture, and chainId.

fix: pass enriched log for projectNotFound error

---

common/evm_block_ref.go
common/evm_block_ref_test.go
common/evm_json_rpc.go

This PR updates the `ExtractEvmBlockReferenceFromRequest` for methods (referenced [here](https://eips.ethereum.org/EIPS/eip-1898)) that currently accept a default block parameter (`blockNumber` HEX string or tag such as `latest`) to additionally support block hashes (as an object).
* `"earliest"`
* `"0x0"`
* `{ "blockNumber": "0x0" }`
* `{ "blockHash": "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3" }`

fix: add blockHash support for certain eth_methods (eip-1898)

---

docs/pages/config/database/evm-json-rpc-cache.mdx
docs/pages/config/projects/selection-policies.mdx

Often users get confused about the default memory-based cache that is enabled. This PR makes it an opt-in feature.

fix: disable caching by default to avoid confusion

---

monitoring/grafana/dashboards/erpc.json

1. Added a datasource variable, fixes #128 
2. Added some general level stats at the top (p95 latency across networks and success rate across networks+upstreams)
3. Cleaned up and divided dashboard into three rows: network-wide stats, cache health and upstream-wide stats

feat(o11y): add datasource variable, rows and stats

---

cmd/erpc/main_test.go
common/config.go
common/defaults.go
common/defaults_test.go
common/evm_block_ref.go
common/evm_block_ref_test.go
docs/pages/config/database/evm-json-rpc-cache.mdx
docs/pages/config/example.mdx
erpc/http_server_test.go
erpc/networks.go
erpc/projects_test.go
upstream/http_json_rpc_client.go
upstream/upstream.go

Based on various users' experiences certain defaults are a bit 'too much magic' and they surprise or confuse users:

feat: simplify various default configs to be more explicit

---

common/script/object.go
erpc/erpc.go

Allow to pass js/ts records for map object (useful for the `methods` config properties in the `evmJsonRpcCache`)
Add a new admin endpoint `erpc_config` to get the current config. Useful to check and debug that the current erpc config matches the one provided (especially for dynamic js/ts stuff)

feat: allow js/ts Map objects in config

---

common/defaults_test.go
common/validation.go

Fix config validation when only providers are passed as upstreams. Behind the scenes eRPC handles converting theprovider-based upstreams (e.g Alchemy) to provider, so the validation should not fail.
```
...
projects:
- id: main
upstreams:
- endpoint: "alchemy://API_KEY"
```

fix: validation when only providers are passed as upstreams

---

architecture/evm/error_normalizer.go
architecture/evm/eth_getLogs.go
architecture/evm/eth_getLogs_test.go
clients/http_json_rpc_client.go
cmd/erpc/main.go
common/architecture_evm.go
common/config.go
common/defaults.go
common/errors.go
common/response.go
common/validation.go
docs/pages/_meta.js
docs/pages/config/projects/upstreams.mdx
docs/pages/free.mdx
erpc/http_server_test.go
erpc/init.go
erpc/networks.go
erpc/networks_test.go
pnpm-lock.yaml
thirdparty/alchemy.go
thirdparty/quicknode.go
thirdparty/repository.go
typescript/cli/package.json
upstream/failsafe.go
upstream/registry.go
upstream/upstream.go
util/bytes.go

fix: various robustness edge-cases

---

Makefile
architecture/evm/eth_getLogs.go
architecture/evm/eth_getLogs_test.go
common/json_rpc.go
common/response.go
summary.json
test/k6/evm-historical-randomized.js
util/bytes.go

Fix an issue when block ranges are way too high, and multiple nested splits are required merging

fix: merge results correctly on multiple nested getLogs splits

---

architecture/evm/evm_state_poller.go

Add a fallback in the `EvmStatePoller` to handle cases where `eth_syncing` is returned as a double-encoded JSON string. This prevents parsing errors when certain upstream providers incorrectly wrap the syncing object in quotes.
```
{
"level": "error",
"projectId": "main",
"upstreamId": "https://rpc.graffiti.farm#redacted=fb0b0",
"component": "evmStatePoller",
"error": "ErrEvmStatePoller: cannot parse syncing state result (must be boolean or object) -> ({\"result\":\"{\\\"startingBlock\\\":\\\"0x146e799\\\",\\\"currentBlock\\\":\\\"0x146e79b\\\",\\\"highestBlock\\\":\\\"0x146e79b\\\",\\\"warpChunksAmount\\\":null,\\\"warpChunksProcessed\\\":null}\"})",
"time": 1741278283561,
"message": "failed to poll evm state for upstream https://rpc.graffiti.farm#redacted=fb0b0"
}
```

fix: handle quoted syncing state responses in EVM state poller

---

common/defaults.go
erpc/projects.go

`eth_getBlockReceipts` supports passing an object containing `blockNumber` or `blockHash` as param as well. 
We were only supporting a basic blockNumber or blockTag as string, but with this change, we also support this as well.
```
{
"jsonrpc": "2.0",
"method": "eth_getBlockReceipts",
"params": [
{
"blockHash": "0xe869f24fc3596bfaf3d046e5db65c0fc879f6e634fa702bc16f88b37032b19a8"
}
],
"id": 703
}
```
```
{
"jsonrpc": "2.0",
"id": 703,
"result": [
{
"blockHash": "0xe869f24fc3596bfaf3d046e5db65c0fc879f6e634fa702bc16f88b37032b19a8",
"blockNumber": "0x14f87d8",
"contractAddress": null,
...
}
```

fix: enhance eth_getBlockReceipts request reference handling

---

architecture/evm/error_normalizer.go
common/errors.go
erpc/http_server.go

- Expose `X-Erpc-Upstream` header even for error responses
- Add more error cases for getLogs too-large scenarios, and avoid wrongly handling "invalid block range"
- Expose `X-Erpc-Version` and `X-Erpc-Commit` headers for easier debugging

fix: expose upstream header even for error responses

---

common/validation.go

Updating upstream `JsonRPC.SupportsBatch` config validation so `batchMaxWait` and `batchMaxSize` are required only when `supportsBatch` is true—matching our logic [here](https://github.com/erpc/erpc/blob/0fecb7c592f21ae998dd405ff9af352c1d945271/clients/http_json_rpc_client.go#L91).

fix: correct supportsBatch validation

---

architecture/evm/evm_state_poller.go

Fixing the `eth_syncing` parsing logic so that any object containing the keys startingBlock, currentBlock, or highestBlock is recognized as syncing: https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_syncing

fix: check eth_syncing result to return syncing true state properly

---

common/defaults.go

We were not applying `ProxyPool` and `Headers` from `upstreamDefaults` to individual ones

fix: add ProxyPool and Headers to upstreamDefaults

---

.gitignore
architecture/evm/error_normalizer.go
common/config.go
common/errors.go
docs/pages/config/failsafe.mdx
docs/public/llms.txt
erpc/http_server_test.go
erpc/networks.go
erpc/networks_test.go
thirdparty/alchemy.go
thirdparty/quicknode.go
upstream/failsafe.go

Since when we have client error it'll not be retried properly towards other upstreams, it would be useful to have a mechanism for such retryable client-side errors.

fix: retryable client side errors mechanism

---

.github/workflows/benchmark.yml
.github/workflows/release.yml
.github/workflows/test.yml
.vscode/launch.json
Dockerfile
Dockerfile.fake
architecture/evm/eth_getLogs_test.go
clients/http_json_rpc_client.go
common/errors.go
data/redis.go
docs/pages/config/example.mdx
docs/pages/config/failsafe.mdx
docs/pages/config/projects/networks.mdx
docs/pages/operation/tracing.mdx
erpc/http_server.go
erpc/http_server_test.go
erpc/networks.go
erpc/networks_test.go
erpc/projects.go
upstream/failsafe.go
util/initializer.go

Return last empty response instead of `all upstream attempts failed` error when all upstreams return empty results.
fixes #214

fix: handle cases where all upstream responses are empty

---

architecture/evm/error_normalizer.go
architecture/evm/evm_state_poller.go

These behaviors have been seen on Sonic and Oasis chains, and probably others.

fix: skip polling when upstream does not support finalized/latest tags

---

thirdparty/pimlico.go

While testing eRPC's Pimlico provider we faced a nil pointer issue caused by the Pimlico `GenericHttpJsonRpcClient` receiving a nil URL, copied at the end of this description. The line numbers are not accurate because I added a few debugging statements. We've added a `generateUrl` to Pimlico method based on the one from Thirdweb, and passed it to the client builder.
Our configuration was:
```yaml
#...
networks:
- architecture: evm
alias: ethereum
evm:
chainId: 1
#...
providers:
- vendor: pimlico
settings:
apiKey: <our api key>
upstreamIdTemplate: "<NETWORK>-<PROVIDER>"
#...
upstreams:
- endpoint: pimlico://<our api key>
```
And the output:
```shell
mikel@laptop - github.com/erpc/erpc ‹main*› $ make run
{"level":"info","action":"erpc","version":"dev","commit":"none","time":1748271708240,"me …
```

fix: correctly generate Pimlico URL when creating its provider

---

thirdparty/envio.go

Envio recently updated their RPC endpoint with an optional [api token](https://docs.envio.dev/docs/HyperSync/hyperrpc-supported-networks) suffix at the end of the rpc url.
This PR read an optional `apiKey` prop in the vendor settings of the envio provider, and if present, add that to the rpc url

feat: add apiKey prop for envio rpc

---

common/json_rpc.go
erpc/networks.go
erpc/networks_consensus_test.go

We observed a scenario where with upstreams for avalanche fuji configured pointing at quicknode (finalized blocks only) and alchemy (unfinalized blocks) which were frequent reorgs which we weren't expecting to handle due to previously _only_ having processed finalised blocks due to running on nodes with the configuration for [allow-unfinalized-queries](https://build.avax.network/docs/nodes/chain-configs/c-chain#allow-unfinalized-queries) was defaulted to false.
Whilst the introduction of alchemy as a provider which allows for unfinalized blocks explained how we were seeing these blocks in the first place, it didn't explain _how_ they were getting past the consensus functionality recently introduced https://github.com/erpc/erpc/pull/265 which we've been running experimentally.
Digging …

fix: retried consensus executions bypassing consensus

---

.dockerignore
Dockerfile
Makefile
common/config.go

The application was not properly displaying version and commit SHA information in response headers. The build arguments `VERSION` and `COMMIT_SHA` defined in the Dockerfile were not being correctly injected into the Go variables `ErpcVersion` and `ErpcCommitSha`.
Current behavior:
- `X-ERPC-Version` header always shows "dev"
- `X-ERPC-Commit` header always shows "none"
Root cause:
The `-X` flags in `LDFLAGS` were using incorrect package paths (`common.ErpcVersion`) instead of the full module path required by Go's linker.
Updated the `LDFLAGS` in the Dockerfile to use the correct full module paths:
```diff
- LDFLAGS="-w -s -X common.ErpcVersion=${VERSION} -X common.ErpcCommitSha=${COMMIT_SHA}"
+ LDFLAGS="-w -s -X github.com/erpc/erpc/common.ErpcVersion=${VERSION} -X …
```

fix: docker build arguments for version and commit sha injection

---

common/config.go
common/defaults.go
common/defaults_test.go
erpc/networks.go

- Add project/network-level statefulMethods config with sensible EVM defaults
- Permit filter-related stateful methods when exactly one upstream is targeted (or only one exists)
- Return descriptive error when multiple upstreams are targeted for stateful methods
- Keep eth_accounts/eth_sign unsupported

feat: allow stateful rpc methods with single-target UseUpstream directive
